#name: Android Lint
#
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]
#  workflow_dispatch:
#
#jobs:
#  lint:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Make gradlew executable
#        run: chmod +x ./gradlew
#
#      - name: Run Lint
#        run: ./gradlew lintDebug
#
#      - name: Upload lint html report
#        uses: actions/upload-artifact@v2
#        if: ${{ always() }}
#        with:
#          name: lint.html
#          path: app/build/reports/lint-results-debug.html